### PR TITLE
fix(tailwindcss_ls): automatic add tailwind global css file to experimental.configFile in order to support Tailwind v4

### LINKED ISSUE #4204: Tailwindcss LSP: Invalid `experimental.configFile` configuration, not initializing
### Description

tailwindcss lsp doesn't work well with tailwindcss v4 (removal of tailwind config file). I read this [issue](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1377) from their intellisense and tried to fix it in neovim with
```lua
vim.lsp.config('tailwindcss', {
        settings = {
          tailwindCSS = {
            experimental = {
              configFile = vim.fs.find(
                { "globals.css" },
                { path = vim.fs.joinpath(LazyVim.root.get(), "packages/ui/src/styles") }
              ),
            },
          },
        },
      }
)
```
but the lsp.log gave me this message:
```txt
 Invalid `experimental.configFile` configuration, not initializing
```

### PR DESCRIPTION
**Pull request by CaoKha**
## Summary
- Tailwind v4 no longer requires a `tailwind.config.js` file, but the LSP still expects a global stylesheet to be provided via `experimental.configFile`. This PR automatically locates a stylesheet in the project root that contains `@import 'tailwindcss';` and assigns its path to `experimental.configFile`. This ensures proper Tailwind v4 support without requiring a manual config file.
- Trying to close #4204

### CODE REVIEW

File: lsp/tailwindcss.lua [hunk 1]
```diff
@@ -100,6 +137,9 @@ return {
         htmlangular = 'html',
         templ = 'html',
       },
+      experimental = {
+        configFile = find_tailwind_global_css(),
```
Comment (justinmk) [inline lsp/tailwindcss.lua]: This will get executed when the module is loaded, which depends on the user config/plugins/etc. Why not do this in `before_init`? There is already a `before_init` below, just move this there ...

File: lsp/tailwindcss.lua [hunk 2]
```diff
@@ -6,6 +6,43 @@
...
+    path = root,
+    type = 'file',
+    limit = math.huge, -- search full tree
+  })
+
+  for _, path in ipairs(files) do
+    local f = io.open(path, 'r')
+    if f then
+      local content = f:read('*a')
+      f:close()
```
Comment (justinmk) [inline lsp/tailwindcss.lua]:
```suggestion
    local content = vim.fn.readblob(path)
```

**Comment by justinmk** [comment]
https://github.com/neovim/nvim-lspconfig/pull/4222#discussion_r2896459541 still hasn't been resolved. did you try moving the call to `before_init` ?

**Comment by CaoKha** [comment]
> [#4222 (comment)](https://github.com/neovim/nvim-lspconfig/pull/4222#discussion_r2896459541) still hasn't been resolved. did you try moving the call to `before_init` ?

I think adding the neovim upstream rewrite my last modification. I re-added it on the last commit. It should be good now.

File: lsp/tailwindcss.lua [hunk 3]
```diff
@@ -113,6 +146,9 @@ return {
     if not config.settings.editor.tabSize then
       config.settings.editor.tabSize = vim.lsp.util.get_effective_tabstop()
     end
+    config.settings.tailwindCSS.experimental = {
+      configFile = find_tailwind_global_css(),
+    }
```
Comment (justinmk) [inline lsp/tailwindcss.lua]: is `config.settings.tailwindCSS` guaranteed to exist? also, this will overwrite any existing `experimental` object.

you need to do something like this:


```suggestion
    config.settings.tailwindCSS = config.settings.tailwindCSS or {}
    config.settings.tailwindCSS.experimental = config.settings.tailwindCSS.experimental or {}
    config.settings.tailwindCSS.experimental.configFile = find_tailwind_global_css()
```

**Comment by justinmk** [comment]
> I think adding the neovim upstream rewrite my last modification.

should be fixed with https://github.com/neovim/nvim-lspconfig/pull/4366 , please rebase

**Comment by CaoKha** [comment]
> > I think adding the neovim upstream rewrite my last modification.
> 
> should be fixed with #4366 , please rebase

rebased

**Comment by CaoKha** [comment]
my bad. Should rebase against upstream. Done! The github-actions[bot] added lines in rust_analyzer.lua should be gone now.

File: lsp/tailwindcss.lua [hunk 4]
```diff
@@ -113,6 +146,10 @@ return {
     if not config.settings.editor.tabSize then
       config.settings.editor.tabSize = vim.lsp.util.get_effective_tabstop()
     end
+    config.settings.tailwindCSS = config.settings.tailwindCSS or {}
+    config.settings.tailwindCSS.experimental = config.settings.tailwindCSS.experimental or {}
+    config.settings.tailwindCSS.experimental.configFile = config.settings.tailwindCSS.experimental.configFile
+      or find_tailwind_global_css()
```
Comment (justinmk) [inline lsp/tailwindcss.lua:152]: for reference, alternative way:

```lua
config.settings = vim.tbl_deep_extend(
  'force',
  config.settings,
  { tailwindCSS = { experimental = { configFile = find_tailwind_global_css() } } }
)
```

**Comment by justinmk** [comment]
reverted:

- https://github.com/neovim/nvim-lspconfig/pull/4376
