### PR TITLE
fix(ui): gracefully handle null filetypes

### LINKED ISSUE #1215: LspInfo gives error and show empty floating buffer.
- `nvim --version`: 0.6.0-dev+210-g6751d6254
- nvim-lspconfig version(commit hash): afc4571dc8c92948131d97f9a8a1512613c5d533
- What language server (If the problem is related to a specific language server): It doesn't look like a particular language server problem because this error is happening regardless of the language server.
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
- Is the problem isolated to a particular language server: No
- Operating system/version: ManjaroLinux / 21.1.0

### How to reproduce the problem from neovim startup
* Run `nvim init.lua` in terminal.
* Run `:LspInfo` in command line mode.

### Actual behaviour
When I run `:LspInfo` in nvim it shows error and then an empty floating buffer. And after running `:LspRestart`  and then doing `:LspInfo` it shows no error. When I ran `:LspRestart` it also showed error that time also.

Before this commit there was no error when `:LspInfo` was run.
**From this commit onwards  the error started appearing**: afc4571dc8c92948131d97f9a8a1512613c5d533
**Until this commit there is no error**: 8de7931cf1cb0c20f2db1e29579bfbff910899d4

### Expected behaviour
It should open a floating buffer with lsp information when `:LspInfo` is run.

### Minimal init.vim or init.lua and code sample

I ran the minimal config as it is on a python file and the `:LspInfo` showed no error.

### Health check
<details>
<summary>Checkhealth result</summary>

```

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: bash: configuration checked.
  - INFO: go: configuration checked.
  - INFO: dockerfile: configuration checked.
  - INFO: lua: configuration checked.
  - ERROR: emmet_ls: The given command "emmet-ls" is not executable.
  - INFO: html: configuration checked.
  - INFO: latex: configuration checked.
  - INFO: yaml: configuration checked.
  - INFO: css: configuration checked.
  - INFO: efm: configuration checked.
  - INFO: python: configuration checked.
  - INFO: json: configuration checked.
  - INFO: vue: configuration checked.
  - INFO: graphql: configuration checked.
  - INFO: cpp: configuration checked.
  - INFO: rust: configuration checked.
  - INFO: typescript: configuration checked.
  - ERROR: tailwindcss: The given command "/home/ash/.local/share/nvim/lspinstall/tailwindcss/./node_modules/.bin/tailwindcss-language-server" is not executable.
  - INFO: svelte: configuration checked.
  - INFO: vim: configuration checked.

```
</details>

### LSP log

<details>
<summary>Log file</summary>

```
[ START ] 2021-09-03T01:32:06+0530 ] LSP logging initiated
[ INFO ] 2021-09-03T01:32:06+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:316 ]	"Starting RPC client"	{  args = {},  cmd = "/home/ash/.local/share/nvim/lspinstall/lua/./sumneko-lua-language-server",  extra = {    cwd = "/home/ash/.local/share/nvim/lspinstall/lua"  }}
[ DEBUG ] 2021-09-03T01:32:06+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:829 ]	"LSP[lua]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }          }        },        dynamicRegistration = true      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = true        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }        },        contextSupport = false,        dynamicRegistration = false      },      declaration = {        linkSupport = true      },      definition = {        linkSupport = true      },      documentHighlight = {        dynamicRegistration = false      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }        }      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false      },      implementation = {        linkSupport = true      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 }        }      },      references = {        dynamicRegistration = false      },      rename = {        dynamicRegistration = false,        prepareSupport = true      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          activeParameterSupport = true,          documentationFormat = { "markdown", "plaintext" },          parameterInformation = {            labelOffsetSupport = true          }        }      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false      },      typeDefinition = {        linkSupport = true      }    },    window = {      showDocument = {        support = false      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false        }      },      workDoneProgress = true    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }        }      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" }      },      workspaceFolders = true    }  },  clientInfo = {    name = "Neovim",    version = "0.6.0"  },  initializationOptions = vim.empty_dict(),  processId = 682051,  rootPath = "/home/ash/.config/nvim",  rootUri = "file:///home/ash/.config/nvim",  trace = "off",  workspaceFolders = { {      name = "/home/ash/.config/nvim",      uri = "file:///home/ash/.config/nvim"    } }}
[ DEBUG ] 2021-09-03T01:32:06+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }            }          },          dynamicRegistration = true        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = true          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }          },          contextSupport = false,          dynamicRegistration = false        },        declaration = {          linkSupport = true        },        definition = {          linkSupport = true        },        documentHighlight = {          dynamicRegistration = false        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false        },        implementation = {          linkSupport = true        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 }          }        },        references = {          dynamicRegistration = false        },        rename = {          dynamicRegistration = false,          prepareSupport = true        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            activeParameterSupport = true,            documentationFormat = { "markdown", "plaintext" },            parameterInformation = {              labelOffsetSupport = true            }          }        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false        },        typeDefinition = {          linkSupport = true        }      },      window = {        showDocument = {          support = false        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false          }        },        workDoneProgress = true      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" }        },        workspaceFolders = true      }    },    clientInfo = {      name = "Neovim",      version = "0.6.0"    },    initializationOptions = vim.empty_dict(),    processId = 682051,    rootPath = "/home/ash/.config/nvim",    rootUri = "file:///home/ash/.config/nvim",    trace = "off",    workspaceFolders = { {        name = "/home/ash/.config/nvim",        uri = "file:///home/ash/.config/nvim"      } }  }}
[ INFO ] 2021-09-03T01:32:06+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:316 ]	"Starting RPC client"	{  args = {},  cmd = "/home/ash/.local/share/nvim/lspinstall/efm/./efm-langserver",  extra = {    cwd = "/home/ash/.local/share/nvim/lspinstall/efm"  }}
[ DEBUG ] 2021-09-03T01:32:06+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:829 ]	"LSP[efm]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }          }        },        dynamicRegistration = true      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = true        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }        },        contextSupport = false,        dynamicRegistration = false      },      declaration = {        linkSupport = true      },      definition = {        linkSupport = true      },      documentHighlight = {        dynamicRegistration = false      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }        }      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false      },      implementation = {        linkSupport = true      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 }        }      },      references = {        dynamicRegistration = false      },      rename = {        dynamicRegistration = false,        prepareSupport = true      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          activeParameterSupport = true,          documentationFormat = { "markdown", "plaintext" },          parameterInformation = {            labelOffsetSupport = true          }        }      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false      },      typeDefinition = {        linkSupport = true      }    },    window = {      showDocument = {        support = false      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false        }      },      workDoneProgress = true    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }        }      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" }      },      workspaceFolders = true    }  },  clientInfo = {    name = "Neovim",    version = "0.6.0"  },  initializationOptions = vim.empty_dict(),  processId = 682051,  rootPath = "/home/ash/.config/nvim",  rootUri = "file:///home/ash/.config/nvim",  trace = "off",  workspaceFolders = { {      name = "/home/ash/.config/nvim",      uri = "file:///home/ash/.config/nvim"    } }}
[ DEBUG ] 2021-09-03T01:32:06+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }            }          },          dynamicRegistration = true        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = true          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }          },          contextSupport = false,          dynamicRegistration = false        },        declaration = {          linkSupport = true        },        definition = {          linkSupport = true        },        documentHighlight = {          dynamicRegistration = false        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false        },        implementation = {          linkSupport = true        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 }          }        },        references = {          dynamicRegistration = false        },        rename = {          dynamicRegistration = false,          prepareSupport = true        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            activeParameterSupport = true,            documentationFormat = { "markdown", "plaintext" },            parameterInformation = {              labelOffsetSupport = true            }          }        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false        },        typeDefinition = {          linkSupport = true        }      },      window = {        showDocument = {          support = false        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false          }        },        workDoneProgress = true      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" }        },        workspaceFolders = true      }    },    clientInfo = {      name = "Neovim",      version = "0.6.0"    },    initializationOptions = vim.empty_dict(),    processId = 682051,    rootPath = "/home/ash/.config/nvim",    rootUri = "file:///home/ash/.config/nvim",    trace = "off",    workspaceFolders = { {        name = "/home/ash/.config/nvim",        uri = "file:///home/ash/.config/nvim"      } }  }}
[ ERROR ] 2021-09-03T01:32:06+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/ash/.local/share/nvim/lspinstall/efm/./efm-langserver"	"stderr"	"2021/09/03 01:32:06 efm-langserver: no configuration file\n2021/09/03 01:32:06 efm-langserver: reading on stdin, writing on stdout\n"
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "😺Lua",    tooltip = "Workspace   : \nCached files: 0/0\nMemory usage: 3M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      definitionProvider = true,      textDocumentSync = 1,      workspace = {        workspaceFolders = {          changeNotifications = true,          supported = true        }      }    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "😺Lua",  tooltip = "Workspace   : \nCached files: 0/0\nMemory usage: 3M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "Log path: file:///home/ash/.local/share/nvim/lspinstall/lua/./sumneko-lua/extension/server/log/file_home_ash_.config_nvim.log",    type = 4  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      codeActionProvider = {        codeActionKinds = { "", "quickfix", "refactor.rewrite", "refactor.extract" },        resolveProvider = false      },      completionProvider = {        resolveProvider = true,        triggerCharacters = { "\t", "\n", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ".", ":", "(", "'", '"', "[", ",", "#", "*", "@", "|", "=", "-", "{", " " }      },      definitionProvider = true,      documentHighlightProvider = true,      documentOnTypeFormattingProvider = {        firstTriggerCharacter = "\n"      },      documentSymbolProvider = true,      executeCommandProvider = {        commands = { "lua.removeSpace:682056", "lua.solve:682056", "lua.jsonToLua:682056", "lua.setConfig:682056", "lua.autoRequire:682056" }      },      foldingRangeProvider = true,      hoverProvider = true,      referencesProvider = true,      renameProvider = {        prepareProvider = true      },      signatureHelpProvider = {        triggerCharacters = { "(", "," }      },      textDocumentSync = {        change = 2,        openClose = true      },      typeDefinitionProvider = true,      workspaceSymbolProvider = true    },    serverInfo = {      name = "sumneko.lua"    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/show"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:856 ]	"LSP[efm]"	"server_capabilities"	{  definitionProvider = true,  textDocumentSync = 1,  workspace = {    workspaceFolders = {      changeNotifications = true,      supported = true    }  }}
[ INFO ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:857 ]	"LSP[efm]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = false,    code_lens = false,    code_lens_resolve = false,    completion = false,    declaration = false,    document_formatting = false,    document_highlight = false,    document_range_formatting = false,    document_symbol = false,    execute_command = false,    find_references = false,    goto_definition = true,    hover = false,    implementation = false,    rename = false,    signature_help = false,    signature_help_trigger_characters = {},    text_document_did_change = 1,    text_document_open_close = true,    text_document_save = true,    text_document_save_include_text = false,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = false,    workspace_folder_properties = {      changeNotifications = true,      supported = true    },    workspace_symbol = false  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "lua",      text = "vim.g.python3_host_prog=\"/usr/bin/python3\"\nrequire(\"settings\")\nrequire(\"keymaps\")\nrequire(\"autocmds\")\nrequire(\"commands\")\n\nvim.g.tokyonight_style = \"storm\"\n-- vim.g.onedark_style = \"cool\"\nvim.cmd[[colorscheme tokyonight]]\n\nrequire(\"plugins\")\n-- require(\"plugin-config.statusline\").config()\n-- TODO: lol\n-- If you see two white bulbs it is lspsaga\n-- For the same look as lspsaga for compe\n-- vim.cmd [[nnoremap Q :<C-f>]]\nvim.cmd [[nnoremap <Esc> <cmd>noh<cr>]]\nvim.cmd [[nnoremap g. @:]] -- repeat the last ex command\nvim.cmd [[nnoremap Q @@]] -- repeat the last macro\nvim.cmd [[\nfunction! Syn()\n    \" for id in synstack(line(\".\"), col(\".\"))\n    \"   echo synIDattr(id, \"name\")\n    \" endfor\n    let l:s = synID(line('.'), col('.'), 1) \n    echo synIDattr(l:s, 'name') . ' -> ' . synIDattr(synIDtrans(l:s), 'name')\nendfunction\ncommand! -nargs=0 Syn call Syn()\n]]\n\nvim.cmd [[nmap <leader>rn <Plug>RestNvim]]\nvim.cmd [[nmap <leader>rnp <Plug>RestNvimPreview]]\n\n\n-- TODO: learn how to use multicursor\nvim.cmd[[\n    let g:VM_mouse_mappings = 1\n    nmap   <C-LeftMouse>         <Plug>(VM-Mouse-Cursor)\n    nmap   <C-RightMouse>        <Plug>(VM-Mouse-Word)\n    nmap   <M-C-RightMouse>      <Plug>(VM-Mouse-Column)\n]]\n\nvim.cmd [[nnoremap <leader>fi :lua require('telescope').extensions.arecibo.websearch()]]\nvim.opt.lazyredraw = true\n\nfunction TabnineConfig()\n    local scratchBuffer = vim.fn.bufnr(\"tabnine-buffer\",1)\n    vim.fn.setbufvar(scratchBuffer,\"&buftype\",\"nofile\")\n    local curBuf = vim.fn.bufnr(\"\")\n    vim.cmd(\"execute\" .. scratchBuffer .. \"\\\"buffer\\\"\")\n    vim.cmd(\"execute\" .. curBuf .. \"\\\"buffer\\\"\")\n    vim.fn.setbufline(scratchBuffer,1,\"Tabnine::config\")\nend\n\nfunction Hello()\n    print \"hi\"\nend\nvim.cmd[[\n    function! OpenPDFCitekey()\n       let kcmd = 'kitty --single-instance --instance-group=1 '\n       let kcmd = kcmd . 'termpdf.py --nvim-listen-address '\n       let kcmd = kcmd . $NVIM_LISTEN_ADDRESS . ' '\n       let key=expand('<cword>')\n       keepjumps normal! ww\n       let page=expand('<cword>')\n       if page ==? 'p'\n           keepjumps normal! ww\n           let page=expand('<cword>')\n       endif\n       keepjumps normal! bbb\n       let kcmd = kcmd . '--open ' . key . ' '\n       if page\n           let kcmd = kcmd . '-p ' . page \n       endif\n       exe \"!\" . kcmd\n    endfunction\n]]\n\nvim.cmd [[nnoremap : ;]]\nvim.cmd [[nnoremap ; :]]\nvim.cmd [[xnoremap : ;]]\nvim.cmd [[xnoremap ; :]]\n-- vim.cmd [[set scrolloff=10]]\nvim.cmd [[nnoremap <leader><leader> <c-^>]]\nvim.lsp.set_log_level(\"debug\")\n",      uri = "file:///home/ash/.config/nvim/init.lua",      version = 0    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"window/logMessage"	{  message = "Log path: file:///home/ash/.local/share/nvim/lspinstall/lua/./sumneko-lua/extension/server/log/file_home_ash_.config_nvim.log",  type = 4}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"window/logMessage"	{  client_id = 1,  params = {    message = "Log path: file:///home/ash/.local/share/nvim/lspinstall/lua/./sumneko-lua/extension/server/log/file_home_ash_.config_nvim.log",    type = 4  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:429 ]	"Log path: file:///home/ash/.local/share/nvim/lspinstall/lua/./sumneko-lua/extension/server/log/file_home_ash_.config_nvim.log"
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "workspace/didChangeConfiguration",  params = {    settings = {      Lua = {        diagnostics = {          globals = { "vim" }        },        runtime = {          path = { "./?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/?.lua", "/usr/local/share/lua/5.1/?.lua", "/usr/local/share/lua/5.1/?/init.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua" },          version = "LuaJIT"        },        telemetry = {          enable = false        },        workspace = {          ignoreDir = { ".vscode" },          library = {            ["/usr/share/nvim/runtime/lua"] = true,            ["/usr/share/nvim/runtime/lua/vim/lsp"] = true          }        }      }    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:856 ]	"LSP[lua]"	"server_capabilities"	{  codeActionProvider = {    codeActionKinds = { "", "quickfix", "refactor.rewrite", "refactor.extract" },    resolveProvider = false  },  completionProvider = {    resolveProvider = true,    triggerCharacters = { "\t", "\n", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ".", ":", "(", "'", '"', "[", ",", "#", "*", "@", "|", "=", "-", "{", " " }  },  definitionProvider = true,  documentHighlightProvider = true,  documentOnTypeFormattingProvider = {    firstTriggerCharacter = "\n"  },  documentSymbolProvider = true,  executeCommandProvider = {    commands = { "lua.removeSpace:682056", "lua.solve:682056", "lua.jsonToLua:682056", "lua.setConfig:682056", "lua.autoRequire:682056" }  },  foldingRangeProvider = true,  hoverProvider = true,  referencesProvider = true,  renameProvider = {    prepareProvider = true  },  signatureHelpProvider = {    triggerCharacters = { "(", "," }  },  textDocumentSync = {    change = 2,    openClose = true  },  typeDefinitionProvider = true,  workspaceSymbolProvider = true}
[ INFO ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:857 ]	"LSP[lua]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = {      codeActionKinds = { "", "quickfix", "refactor.rewrite", "refactor.extract" },      resolveProvider = false    },    code_lens = false,    code_lens_resolve = false,    completion = true,    declaration = false,    document_formatting = false,    document_highlight = true,    document_range_formatting = false,    document_symbol = true,    execute_command = true,    find_references = true,    goto_definition = true,    hover = true,    implementation = false,    rename = true,    signature_help = true,    signature_help_trigger_characters = { "(", "," },    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = false,    text_document_save_include_text = false,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = true,    workspace_folder_properties = {      changeNotifications = false,      supported = false    },    workspace_symbol = true  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "lua",      text = "vim.g.python3_host_prog=\"/usr/bin/python3\"\nrequire(\"settings\")\nrequire(\"keymaps\")\nrequire(\"autocmds\")\nrequire(\"commands\")\n\nvim.g.tokyonight_style = \"storm\"\n-- vim.g.onedark_style = \"cool\"\nvim.cmd[[colorscheme tokyonight]]\n\nrequire(\"plugins\")\n-- require(\"plugin-config.statusline\").config()\n-- TODO: lol\n-- If you see two white bulbs it is lspsaga\n-- For the same look as lspsaga for compe\n-- vim.cmd [[nnoremap Q :<C-f>]]\nvim.cmd [[nnoremap <Esc> <cmd>noh<cr>]]\nvim.cmd [[nnoremap g. @:]] -- repeat the last ex command\nvim.cmd [[nnoremap Q @@]] -- repeat the last macro\nvim.cmd [[\nfunction! Syn()\n    \" for id in synstack(line(\".\"), col(\".\"))\n    \"   echo synIDattr(id, \"name\")\n    \" endfor\n    let l:s = synID(line('.'), col('.'), 1) \n    echo synIDattr(l:s, 'name') . ' -> ' . synIDattr(synIDtrans(l:s), 'name')\nendfunction\ncommand! -nargs=0 Syn call Syn()\n]]\n\nvim.cmd [[nmap <leader>rn <Plug>RestNvim]]\nvim.cmd [[nmap <leader>rnp <Plug>RestNvimPreview]]\n\n\n-- TODO: learn how to use multicursor\nvim.cmd[[\n    let g:VM_mouse_mappings = 1\n    nmap   <C-LeftMouse>         <Plug>(VM-Mouse-Cursor)\n    nmap   <C-RightMouse>        <Plug>(VM-Mouse-Word)\n    nmap   <M-C-RightMouse>      <Plug>(VM-Mouse-Column)\n]]\n\nvim.cmd [[nnoremap <leader>fi :lua require('telescope').extensions.arecibo.websearch()]]\nvim.opt.lazyredraw = true\n\nfunction TabnineConfig()\n    local scratchBuffer = vim.fn.bufnr(\"tabnine-buffer\",1)\n    vim.fn.setbufvar(scratchBuffer,\"&buftype\",\"nofile\")\n    local curBuf = vim.fn.bufnr(\"\")\n    vim.cmd(\"execute\" .. scratchBuffer .. \"\\\"buffer\\\"\")\n    vim.cmd(\"execute\" .. curBuf .. \"\\\"buffer\\\"\")\n    vim.fn.setbufline(scratchBuffer,1,\"Tabnine::config\")\nend\n\nfunction Hello()\n    print \"hi\"\nend\nvim.cmd[[\n    function! OpenPDFCitekey()\n       let kcmd = 'kitty --single-instance --instance-group=1 '\n       let kcmd = kcmd . 'termpdf.py --nvim-listen-address '\n       let kcmd = kcmd . $NVIM_LISTEN_ADDRESS . ' '\n       let key=expand('<cword>')\n       keepjumps normal! ww\n       let page=expand('<cword>')\n       if page ==? 'p'\n           keepjumps normal! ww\n           let page=expand('<cword>')\n       endif\n       keepjumps normal! bbb\n       let kcmd = kcmd . '--open ' . key . ' '\n       if page\n           let kcmd = kcmd . '-p ' . page \n       endif\n       exe \"!\" . kcmd\n    endfunction\n]]\n\nvim.cmd [[nnoremap : ;]]\nvim.cmd [[nnoremap ; :]]\nvim.cmd [[xnoremap : ;]]\nvim.cmd [[xnoremap ; :]]\n-- vim.cmd [[set scrolloff=10]]\nvim.cmd [[nnoremap <leader><leader> <c-^>]]\nvim.lsp.set_log_level(\"debug\")\n",      uri = "file:///home/ash/.config/nvim/init.lua",      version = 0    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/show"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  bufnr = 1,  client_id = 2,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/init.lua"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  bufnr = 1,  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/init.lua"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/init.lua",    version = 0  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  method = "workspace/configuration",  params = {    items = { {        scopeUri = "file:///home/ash/.config/nvim",        section = "Lua"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.associations"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.exclude"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.semanticHighlighting.enabled"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.acceptSuggestionOnEnter"      } }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "😺Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 0/0\nMemory usage: 3M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 2,  jsonrpc = "2.0",  method = "workspace/configuration",  params = {    items = { {        scopeUri = "file:///home/ash/.config/nvim",        section = "Lua"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.associations"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.exclude"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.semanticHighlighting.enabled"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.acceptSuggestionOnEnter"      } }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/init.lua",  version = 0}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 2,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/init.lua",    version = 0  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:691 ]	"server_request"	"workspace/configuration"	{  items = { {      scopeUri = "file:///home/ash/.config/nvim",      section = "Lua"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "files.associations"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "files.exclude"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "editor.semanticHighlighting.enabled"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "editor.acceptSuggestionOnEnter"    } }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:694 ]	"server_request: found handler for"	"workspace/configuration"
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"workspace/configuration"	{  client_id = 1,  params = {    items = { {        scopeUri = "file:///home/ash/.config/nvim",        section = "Lua"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.associations"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.exclude"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.semanticHighlighting.enabled"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.acceptSuggestionOnEnter"      } }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:507 ]	"server_request: callback result"	{  result = { {      diagnostics = {        globals = { "vim" }      },      runtime = {        path = { "./?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/?.lua", "/usr/local/share/lua/5.1/?.lua", "/usr/local/share/lua/5.1/?/init.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua" },        version = "LuaJIT"      },      telemetry = {        enable = false      },      workspace = {        ignoreDir = { ".vscode" },        library = {          ["/usr/share/nvim/runtime/lua"] = true,          ["/usr/share/nvim/runtime/lua/vim/lsp"] = true        }      }    }, vim.NIL, vim.NIL, vim.NIL, vim.NIL },  status = true}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  result = { {      diagnostics = {        globals = { "vim" }      },      runtime = {        path = { "./?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/?.lua", "/usr/local/share/lua/5.1/?.lua", "/usr/local/share/lua/5.1/?/init.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua" },        version = "LuaJIT"      },      telemetry = {        enable = false      },      workspace = {        ignoreDir = { ".vscode" },        library = {          ["/usr/share/nvim/runtime/lua"] = true,          ["/usr/share/nvim/runtime/lua/vim/lsp"] = true        }      }    }, vim.NIL, vim.NIL, vim.NIL, vim.NIL }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "😺Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 0/0\nMemory usage: 3M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:691 ]	"server_request"	"workspace/configuration"	{  items = { {      scopeUri = "file:///home/ash/.config/nvim",      section = "Lua"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "files.associations"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "files.exclude"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "editor.semanticHighlighting.enabled"    }, {      scopeUri = "file:///home/ash/.config/nvim",      section = "editor.acceptSuggestionOnEnter"    } }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:694 ]	"server_request: found handler for"	"workspace/configuration"
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"workspace/configuration"	{  client_id = 1,  params = {    items = { {        scopeUri = "file:///home/ash/.config/nvim",        section = "Lua"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.associations"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "files.exclude"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.semanticHighlighting.enabled"      }, {        scopeUri = "file:///home/ash/.config/nvim",        section = "editor.acceptSuggestionOnEnter"      } }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:507 ]	"server_request: callback result"	{  result = { {      diagnostics = {        globals = { "vim" }      },      runtime = {        path = { "./?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/?.lua", "/usr/local/share/lua/5.1/?.lua", "/usr/local/share/lua/5.1/?/init.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua" },        version = "LuaJIT"      },      telemetry = {        enable = false      },      workspace = {        ignoreDir = { ".vscode" },        library = {          ["/usr/share/nvim/runtime/lua"] = true,          ["/usr/share/nvim/runtime/lua/vim/lsp"] = true        }      }    }, vim.NIL, vim.NIL, vim.NIL, vim.NIL },  status = true}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 2,  jsonrpc = "2.0",  result = { {      diagnostics = {        globals = { "vim" }      },      runtime = {        path = { "./?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/?.lua", "/usr/local/share/lua/5.1/?.lua", "/usr/local/share/lua/5.1/?/init.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?.lua", "/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua", "/home/ash/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua" },        version = "LuaJIT"      },      telemetry = {        enable = false      },      workspace = {        ignoreDir = { ".vscode" },        library = {          ["/usr/share/nvim/runtime/lua"] = true,          ["/usr/share/nvim/runtime/lua/vim/lsp"] = true        }      }    }, vim.NIL, vim.NIL, vim.NIL, vim.NIL }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "workspace/semanticTokens/refresh",  params = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"workspace/semanticTokens/refresh"	nil
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:897 ]	"LSP[lua]"	"client.request"	1	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    end = <1>{      character = 0,      line = 0    },    start = <table 1>  },  textDocument = {    uri = "file:///home/ash/.config/nvim/init.lua"  }}	<function 1>	1
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 2,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      end = <1>{        character = 0,        line = 0      },      start = <table 1>    },    textDocument = {      uri = "file:///home/ash/.config/nvim/init.lua"    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 2,  jsonrpc = "2.0",  result = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 3,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = 2  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      cancellable = false,      kind = "begin",      percentage = 0,      title = "Loading workspace"    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:691 ]	"server_request"	"window/workDoneProgress/create"	{  token = 2}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:694 ]	"server_request: found handler for"	"window/workDoneProgress/create"
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"window/workDoneProgress/create"	{  client_id = 1,  params = {    token = 2  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:507 ]	"server_request: callback result"	{  result = vim.NIL,  status = true}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 3,  jsonrpc = "2.0",  result = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    cancellable = false,    kind = "begin",    percentage = 0,    title = "Loading workspace"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      cancellable = false,      kind = "begin",      percentage = 0,      title = "Loading workspace"    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "2/80",      percentage = 1    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "2/80",    percentage = 1  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "2/80",      percentage = 1    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "😺Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 2/2\nMemory usage: 5M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "😺Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 2/2\nMemory usage: 5M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "23/80",      percentage = 27    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "23/80",    percentage = 27  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "23/80",      percentage = 27    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "$(loading~spin)Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 32/32\nMemory usage: 8M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "$(loading~spin)Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 32/32\nMemory usage: 8M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "35/80",      percentage = 42    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "35/80",    percentage = 42  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "35/80",      percentage = 42    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "46/80",      percentage = 56    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "46/80",    percentage = 56  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "46/80",      percentage = 56    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "$(loading~spin)Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 51/51\nMemory usage: 14M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "$(loading~spin)Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 51/51\nMemory usage: 14M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "52/80",      percentage = 63    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "52/80",    percentage = 63  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "52/80",      percentage = 63    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "54/80",      percentage = 66    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "54/80",    percentage = 66  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "54/80",      percentage = 66    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "$(loading~spin)Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 54/54\nMemory usage: 22M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "$(loading~spin)Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 54/54\nMemory usage: 22M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "55/80",      percentage = 67    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "55/80",    percentage = 67  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "55/80",      percentage = 67    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "57/80",      percentage = 70    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "57/80",    percentage = 70  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "57/80",      percentage = 70    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "$(loading~spin)Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 57/57\nMemory usage: 23M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "$(loading~spin)Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 57/57\nMemory usage: 23M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "60/80",      percentage = 73    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "60/80",    percentage = 73  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "60/80",      percentage = 73    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "$(loading~spin)Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 64/64\nMemory usage: 36M\n"  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "$(loading~spin)Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 64/64\nMemory usage: 36M\n"}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "65/80",      percentage = 80    }  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "65/80",    percentage = 80  }}
[ DEBUG ] 2021-09-03T01:32:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "65/80",      percentage = 80    }  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "71/80",      percentage = 87    }  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "71/80",    percentage = 87  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "71/80",      percentage = 87    }  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "report",      message = "72/80",      percentage = 88    }  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "report",    message = "72/80",    percentage = 88  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "report",      message = "72/80",      percentage = 88    }  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "$(loading~spin)Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 72/72\nMemory usage: 36M\n"  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "$(loading~spin)Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 72/72\nMemory usage: 36M\n"}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "😺Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 72/72\nMemory usage: 36M\n"  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "😺Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 72/72\nMemory usage: 36M\n"}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 2,    value = {      kind = "end"    }  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/progress"	{  token = 2,  value = {    kind = "end"  }}
[ DEBUG ] 2021-09-03T01:32:08+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 2,    value = {      kind = "end"    }  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/init.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/init.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/init.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/autocmds.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/commands.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/autocmds.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/autocmds.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/commands.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/commands.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/highlights.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/highlights.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/highlights.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/keymaps.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/keymaps.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/keymaps.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/format.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/lsp/format.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/format.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/init.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/lsp/init.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/init.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/on-attach.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/lsp/on-attach.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/on-attach.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/servers.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/lsp/servers.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/lsp/servers.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/autosave.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/autosave.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/autosave.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/bufferline.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/bufferline.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/bufferline.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/comments.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/comments.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/comments.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/dashboard.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/dashboard.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/dashboard.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/dial.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/dial.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/dial.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/file-icons.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/file-icons.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/file-icons.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/formatter.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/formatter.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/formatter.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/git-signs.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/git-signs.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/git-signs.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/indent-blankline.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/indent-blankline.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/indent-blankline.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/lspkind.lua"  }}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/lspkind.lua"}
[ DEBUG ] 2021-09-03T01:32:09+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/lspkind.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/lspsaga.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/lspsaga.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/lspsaga.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/markdown-preview.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/markdown-preview.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/markdown-preview.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/neoformat.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/neoformat.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/neoformat.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/nvim-compe.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/nvim-compe.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/nvim-compe.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/nvim-tree.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/nvim-tree.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/nvim-tree.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/rainbow-brackets.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/rainbow-brackets.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/rainbow-brackets.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "err-eq-as-assign",        message = "Should use `==` for equal.",        range = {          end = {            character = 33,            line = 153          },          start = {            character = 32,            line = 153          }        },        severity = 1,        source = "Lua Syntax Check."      }, {        code = "lowercase-global",        message = "Global variable in lowercase initial.",        range = {          end = {            character = 21,            line = 151          },          start = {            character = 12,            line = 151          }        },        severity = 3,        source = "Lua Diagnostics."      }, {        code = "lowercase-global",        message = "Global variable in lowercase initial.",        range = {          end = {            character = 21,            line = 177          },          start = {            character = 12,            line = 177          }        },        severity = 3,        source = "Lua Diagnostics."      } },    uri = "file:///home/ash/.config/nvim/lua/plugin-config/statusline.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      code = "err-eq-as-assign",      message = "Should use `==` for equal.",      range = {        end = {          character = 33,          line = 153        },        start = {          character = 32,          line = 153        }      },      severity = 1,      source = "Lua Syntax Check."    }, {      code = "lowercase-global",      message = "Global variable in lowercase initial.",      range = {        end = {          character = 21,          line = 151        },        start = {          character = 12,          line = 151        }      },      severity = 3,      source = "Lua Diagnostics."    }, {      code = "lowercase-global",      message = "Global variable in lowercase initial.",      range = {        end = {          character = 21,          line = 177        },        start = {          character = 12,          line = 177        }      },      severity = 3,      source = "Lua Diagnostics."    } },  uri = "file:///home/ash/.config/nvim/lua/plugin-config/statusline.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = { {        code = "err-eq-as-assign",        message = "Should use `==` for equal.",        range = {          end = {            character = 33,            line = 153          },          start = {            character = 32,            line = 153          }        },        severity = 1,        source = "Lua Syntax Check."      }, {        code = "lowercase-global",        message = "Global variable in lowercase initial.",        range = {          end = {            character = 21,            line = 151          },          start = {            character = 12,            line = 151          }        },        severity = 3,        source = "Lua Diagnostics."      }, {        code = "lowercase-global",        message = "Global variable in lowercase initial.",        range = {          end = {            character = 21,            line = 177          },          start = {            character = 12,            line = 177          }        },        severity = 3,        source = "Lua Diagnostics."      } },    uri = "file:///home/ash/.config/nvim/lua/plugin-config/statusline.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/telescope.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/telescope.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/telescope.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/todo-comments.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/todo-comments.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/todo-comments.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/treesitter.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugin-config/treesitter.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugin-config/treesitter.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 316          },          start = {            character = 3,            line = 316          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 23,            line = 44          },          start = {            character = 22,            line = 44          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 37          },          start = {            character = 3,            line = 37          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 27,            line = 37          },          start = {            character = 26,            line = 37          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 34,            line = 42          },          start = {            character = 33,            line = 42          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 71          },          start = {            character = 3,            line = 71          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 253          },          start = {            character = 3,            line = 253          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 263          },          start = {            character = 3,            line = 263          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 275          },          start = {            character = 3,            line = 275          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 277          },          start = {            character = 3,            line = 277          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 284          },          start = {            character = 3,            line = 284          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 289          },          start = {            character = 3,            line = 289          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 294          },          start = {            character = 3,            line = 294          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 304          },          start = {            character = 3,            line = 304          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 105          },          start = {            character = 13,            line = 105          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 233          },          start = {            character = 13,            line = 233          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 237          },          start = {            character = 13,            line = 237          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 239          },          start = {            character = 13,            line = 239          }        },        severity = 2,        source = "Lua Diagnostics."      } },    uri = "file:///home/ash/.config/nvim/lua/plugin-config/which-key.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 316        },        start = {          character = 3,          line = 316        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 23,          line = 44        },        start = {          character = 22,          line = 44        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 37        },        start = {          character = 3,          line = 37        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 27,          line = 37        },        start = {          character = 26,          line = 37        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 34,          line = 42        },        start = {          character = 33,          line = 42        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 71        },        start = {          character = 3,          line = 71        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 253        },        start = {          character = 3,          line = 253        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 263        },        start = {          character = 3,          line = 263        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 275        },        start = {          character = 3,          line = 275        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 277        },        start = {          character = 3,          line = 277        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 284        },        start = {          character = 3,          line = 284        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 289        },        start = {          character = 3,          line = 289        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 294        },        start = {          character = 3,          line = 294        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 4,          line = 304        },        start = {          character = 3,          line = 304        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 14,          line = 105        },        start = {          character = 13,          line = 105        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 14,          line = 233        },        start = {          character = 13,          line = 233        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 14,          line = 237        },        start = {          character = 13,          line = 237        }      },      severity = 2,      source = "Lua Diagnostics."    }, {      code = "undefined-global",      message = "Undefined global `O`.",      range = {        end = {          character = 14,          line = 239        },        start = {          character = 13,          line = 239        }      },      severity = 2,      source = "Lua Diagnostics."    } },  uri = "file:///home/ash/.config/nvim/lua/plugin-config/which-key.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = { {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 316          },          start = {            character = 3,            line = 316          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 23,            line = 44          },          start = {            character = 22,            line = 44          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 37          },          start = {            character = 3,            line = 37          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 27,            line = 37          },          start = {            character = 26,            line = 37          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 34,            line = 42          },          start = {            character = 33,            line = 42          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 71          },          start = {            character = 3,            line = 71          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 253          },          start = {            character = 3,            line = 253          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 263          },          start = {            character = 3,            line = 263          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 275          },          start = {            character = 3,            line = 275          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 277          },          start = {            character = 3,            line = 277          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 284          },          start = {            character = 3,            line = 284          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 289          },          start = {            character = 3,            line = 289          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 294          },          start = {            character = 3,            line = 294          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 4,            line = 304          },          start = {            character = 3,            line = 304          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 105          },          start = {            character = 13,            line = 105          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 233          },          start = {            character = 13,            line = 233          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 237          },          start = {            character = 13,            line = 237          }        },        severity = 2,        source = "Lua Diagnostics."      }, {        code = "undefined-global",        message = "Undefined global `O`.",        range = {          end = {            character = 14,            line = 239          },          start = {            character = 13,            line = 239          }        },        severity = 2,        source = "Lua Diagnostics."      } },    uri = "file:///home/ash/.config/nvim/lua/plugin-config/which-key.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugins.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/settings.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/themes/gruvbox.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/themes/onedark.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/themes/tomorrow-night.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/plugins.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/plugins.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/settings.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/settings.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/themes/gruvbox.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/themes/gruvbox.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/themes/onedark.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/themes/onedark.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/lua/themes/tomorrow-night.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/lua/themes/tomorrow-night.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/plugin/packer_compiled.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/ash/.config/nvim/plugin/packer_compiled.lua"}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:455 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/ash/.config/nvim/plugin/packer_compiled.lua"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/status/report",  params = {    text = "😺Lua",    tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 72/72\nMemory usage: 43M\n"  }}
[ DEBUG ] 2021-09-03T01:32:10+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:677 ]	"notification"	"$/status/report"	{  text = "😺Lua",  tooltip = "Workspace   : /home/ash/.config/nvim\nCached files: 72/72\nMemory usage: 43M\n"}
[ DEBUG ] 2021-09-03T01:32:15+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:897 ]	"LSP[lua]"	"client.request"	1	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    end = <1>{      character = 0,      line = 0    },    start = <table 1>  },  textDocument = {    uri = "file:///home/ash/.config/nvim/init.lua"  }}	<function 1>	1
[ DEBUG ] 2021-09-03T01:32:15+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      end = <1>{        character = 0,        line = 0      },      start = <table 1>    },    textDocument = {      uri = "file:///home/ash/.config/nvim/init.lua"    }  }}
[ DEBUG ] 2021-09-03T01:32:15+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 3,  jsonrpc = "2.0",  result = vim.NIL}
[ DEBUG ] 2021-09-03T01:32:18+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:897 ]	"LSP[lua]"	"client.request"	1	"textDocument/codeAction"	{  context = {    diagnostics = {}  },  range = {    end = <1>{      character = 0,      line = 0    },    start = <table 1>  },  textDocument = {    uri = "file:///home/ash/.config/nvim/init.lua"  }}	<function 1>	1
[ DEBUG ] 2021-09-03T01:32:18+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 4,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = {}    },    range = {      end = <1>{        character = 0,        line = 0      },      start = <table 1>    },    textDocument = {      uri = "file:///home/ash/.config/nvim/init.lua"    }  }}
[ DEBUG ] 2021-09-03T01:32:18+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 4,  jsonrpc = "2.0",  result = vim.NIL}

```
</details>

### Errors
<details>
<summary>LspInfo Error</summary>

```

E5108: Error executing lua vim/shared.lua:183: t: expected table, got nil
stack traceback:
	vim/shared.lua:183: in function 'tbl_contains'
	...te/pack/packer/opt/nvim-lspconfig/lua/lspconfig/util.lua:328: in function 'get_active_client_by_ft'
	...te/pack/packer/opt/nvim-lspconfig/lua/lspconfig/util.lua:337: in function 'get_other_matching_providers'
	...k/packer/opt/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:178: in function <...k/packer/opt/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:111>
	...im/site/pack/packer/opt/nvim-lspconfig/lua/lspconfig.lua:21: in function <...im/site/pack/packer/opt/nvim-lspconfig/lua/lspconfig.lua:20>
	[string ":lua"]:1: in main chunk

```

</details>

### Video 

<details>
<summary>Video of Error</summary>

https://user-images.githubusercontent.com/56691622/131915022-55310e1d-74b1-425a-9786-c4d79388f845.mp4

</details>

### PR DESCRIPTION
**Pull request by kylo252**
# Description

Avoid de-referencing a null `client.config.filetypes` entry.

Fixes #1215

## How has this been tested?

Using `minimal_init.lua` and `efm` which doesn't specify a type by default.

### CODE REVIEW

**Comment by lithammer** [comment]
Under what circumstances would you want or have `filetypes = nil`?

**Comment by mjlbach** [comment]
Right now it defaults to bufenter (so all filetypes), so it's technically valid and we should catch it

File: lua/lspconfig/util.lua [hunk 1]
```diff
@@ -321,25 +321,28 @@ function M.find_package_json_ancestor(startpath)
   end)
 end
 
-function M.get_active_client_by_ft(filetype)
+function M.get_active_clients_list_by_ft(filetype)
```
Comment (mjlbach) [inline lua/lspconfig/util.lua:324]: Why the function name change? get_active_clients_by_id is in core

**Comment by lithammer** [comment]
> Right now it defaults to bufenter (so all filetypes), so it's technically valid and we should catch it

Ah wasn't aware of that. Makes sense!

File: lua/lspconfig/util.lua (hunk 1 above)
Comment (kylo252) [reply lua/lspconfig/util.lua:324]: That was my original plan for this, but the name was misleading because it actually only returns a list of client names, and not the client themselves. If we change it to return a table, then we would have to loop again to match the non-active config names. 

I'm okay with either solution.
