### PR TITLE
fix(gdscript): support get the port from env variable

### LINKED ISSUE #2311: Allow customizing gdscript port
### Language server

gdscript

### Requested feature

The gdscript configuration hard-codes 6008 (https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/gdscript.lua), while Godot allows for customizing the port (see screenshot).

image

Since Godot 3 and 4 uses different ports, it would be great to allow customizing the port.

### Other clients which have this feature

Godot's VS Code plugin has an option to change the port.
image

Also it seems CoC has it, however I'm not experienced using it. https://github.com/habamax/vim-godot#setting-up-cocnvim-for-godot-322

### PR DESCRIPTION
**Pull request by glepnir**
support get the port number from env variable `GDSript_Port`

Fix #2311

### CODE REVIEW

File: lua/lspconfig/server_configurations/gdscript.lua [hunk 1]
```diff
@@ -1,9 +1,10 @@
 local util = require 'lspconfig.util'
 
-local cmd = { 'nc', 'localhost', '6008' }
+local port = os.getenv('GDScript_Port') or '6008'
```
Comment (glepnir) [inline lua/lspconfig/server_configurations/gdscript.lua:3]:
```suggestion
local port = os.getenv 'GDScript_Port' or '6008'
```

Comment (glepnir) [inline lua/lspconfig/server_configurations/gdscript.lua:3]:
```suggestion
local port = os.getenv 'GDScript_Port' or '6008'
```
